# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DML | Digital Media Lab 
email: dml@fh-hagenberg.at
description: Digital Media Lab (DML) - advancing the frontiers of digital interactions through innovative research in UX design, spatial computing, large language model applications, web applications, and process mining.
#baseurl: "/pie.fh-hagenberg.at" # the subpath of your site, e.g. /blog
url: "https://digitalmedialab.at" # the base hostname & protocol for your site
#facebook: playful.interactive.environments

# Build settings
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "" #disable excerpts

exclude: [
  "package.json",
  "node_modules",
  "gulpfile"
]

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /projects/:path/
  areas:
    output: true
    permalink: /areas/:path/

defaults:
  - scope:
      type: projects
    values:
      layout: project
  - scope:
      type: areas
    values:
      layout: area
